### ISSUE TITLE
[Icon update]: .gitignore

### ISSUE THREAD

**Issue by mittalyashu** [Yummygum/city-lights-icons-vsc#10]
Why there is a github icon in front of `.gitignore` file?

![2018-09-24_23-10-50](https://user-images.githubusercontent.com/29014463/45968655-38a3ac00-c04f-11e8-9329-953c2501d663.png)

**Comment by noudadrichem** [comment]
We have different icons for Git. Octocat is not someone you wanna fight with 😝

**Comment by mittalyashu** [comment]
Since Git and GitHub are both different, that's why it doesn't make sense to use an octocat.

Why don't you try this icon?

![chrome_2018-09-25_16-34-00](https://user-images.githubusercontent.com/29014463/46011049-49513200-c0e2-11e8-8b61-11a2421b2ff1.png)

**Source:** _https://www.gitignore.io/_

**Comment by noudadrichem** [comment]
Like I said, we have different icons for git in both gray and color. If you're not liking the icon you're able to change it in the source code.

You can find the source code in your root inside the `.vscode/extentions` directory. It's right that it's not the same thing but we do like octocat, it's a wink to Octo 😝.

![image](https://user-images.githubusercontent.com/16288476/46011157-4a279b00-c0c5-11e8-99eb-291f98362bb5.png)
