### ISSUE TITLE
How can I help you to maintain this repo?

### ISSUE THREAD

**Issue by coderdiaz** [Yummygum/city-lights-icons-vsc#15]
Hello, I think this repo is unmaintained since 2018. But this Icon extensions is very cool, How can I help you to maintain this repo?

Cheers,

**Comment by noudadrichem** [comment]
Hi,

What would you like to maintain? It works like a charm right!? I do bug fixes.

**Comment by coderdiaz** [comment]
For add more support with icons, What about it?
