### ISSUE TITLE
Event for select colored or gray icons

### ISSUE THREAD

**Issue by coderdiaz** [Yummygum/city-lights-icons-vsc#2]
Create a toggle event to select a icon theme, using the dropdown in Command Palette.

**Comment by noudadrichem** [comment]
Yeay, nice!

**Comment by noudadrichem** [comment]
Is this something you're working on @coderdiaz

**Comment by coderdiaz** [comment]
Hi @noudadrichem , I'm trying how to make this functionality, I don't have experience creating extensions with VS Code.

**Comment by coderdiaz** [comment]
@noudadrichem It's ready! 😎

**Comment by noudadrichem** [comment]
Nice! I'll take a look at this asap
