### ISSUE TITLE
Publish to open-vsx

### ISSUE THREAD

**Issue by Miezhiko** [Yummygum/city-lights-icons-vsc#26]
Publish icons to open-vsx, please

recently colors theme were published there but not icons

Thank you

**Comment by noudadrichem** [comment]
Hi, Thanks for mentioning!

**Comment by noudadrichem** [comment]
https://open-vsx.org/extension/yummygum/city-lights-icon-vsc

**Comment by Miezhiko** [comment]
@noudadrichem I've got this `Problems parsing file icons file: Comma expected, Comma expected, Closing brace expected` maybe unrelated
