### ISSUE TITLE
Problems parsing file icons file

### ISSUE THREAD

**Issue by Miezhiko** [Yummygum/city-lights-icons-vsc#29]
Error after getting extension

`Problems parsing file icons file: Comma expected, Comma expected, Closing brace expected`

related to https://github.com/Yummygum/city-lights-icons-vsc/issues/26 possibly

**Comment by noudadrichem** [comment]
Weird. I'm gonna investigate. Thanks!

**Comment by Miezhiko** [comment]
https://github.com/Yummygum/city-lights-icons-vsc/commit/1a98d5e70b0c4b1a56edfe593afcca14d33caa1b seems like it solves the issue, thank you

**Comment by noudadrichem** [comment]
Good to hear!
