### ISSUE TITLE
Active Icons not showing color

### ISSUE THREAD

**Issue by BHallPhoto** [Yummygum/city-lights-icons-vsc#3]
I just recently updated, and found these icons afterwards. So I'm not sure if it was the recent updates. Or on my side. But I did disable all other extensions. And the the active file icon was not showing its equivalent color. 
On another note, Really enjoying both the icon, and color theme.

**Comment by noudadrichem** [comment]
Glad you like the theme and the icons. It's true that on VSCode the active file does not show the coloured icon.
