### ISSUE TITLE
License is not declared in package.json

### ISSUE THREAD

**Issue by spoenemann** [Yummygum/city-lights-icons-vsc#33]
The README says this project is subject to CC BY-NC-ND 4.0. Please add the full text of the license to a LICENSE file and add an entry `"license": "CC BY-NC-ND 4.0"` to the package.json.

A license is mandatory for publishing your extension to [Open VSX](https://open-vsx.org/). See the [Open VSX Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) for more details.

**Comment by brianking** [comment]
@noudadrichem has published this extension in the [Open VSX Registry](https://open-vsx.org/extension/yummygum/city-lights-icon-vsc).

The service was recently transferred to the Eclipse Foundation and we want to ensure a seamless transition for our users. To ensure uninterrupted service and more exposure for your extension, I recommend the following.

**To the maintainers**: If you would like to take over publishing to open-vsx.org, here’s how: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**To the current publisher**: Please sign the [Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf). The signing process is [explained in the Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) (steps 1 and 2).

**Claiming ownership of the namespace for your extension(s)**. To find out how to do this, see:
https://github.com/eclipse/openvsx/wiki/Namespace-Access
As owner you can add more namespace members (including service accounts) yourself in https://open-vsx.org/user-settings/namespaces. Note that publishing can be done by any contributor to the extension, namely those you add as namespace members once they have signed the Publisher Agreement as well.

As mentioned above, a license is now mandatory. Once you have added it, be sure to publish a new version of the extension!

Useful links:
[Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf)
[Eclipse Foundation Open VSX Registry Frequently Asked Questions (FAQ)](https://www.eclipse.org/legal/open-vsx-registry-faq/) 

More details are in these recent blog posts:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

Today, there’s growing momentum around open source tools and technologies that support Visual Studio (VS) Code extensions. Leading global organizations are adopting these tools and technologies. This momentum has spurred demand for a marketplace without restrictions and limitations. We hope you join us on this journey as we continue to build the Open VSX community. 
We look forward to continued innovation from you in 2021!

**Comment by brianking** [comment]
@noudadrichem Do you intend to continue to publish to open-vsx.org?

**Comment by noudadrichem** [comment]
Yes

**Comment by noudadrichem** [comment]
I thought this was already published. Missed the whole transfer and need a resign thing. My bad.

**Comment by brianking** [comment]
Yes, I suggest the following steps:

1. Claim the extension namespace
2. Sign the Publisher Agreement
3. Publish a new version of the extension

Instructions for all are listed in my comment above.

Then it will be reactivated. Thanks for your contributions!
