### ISSUE TITLE
Removing the arrow in front of directory

### ISSUE THREAD

**Issue by tobiastimm** [Yummygum/city-lights-icons-vsc#4]
Hey there,

great icon theme! Would it be possible to remove the arrow in front of the directories or create a separate one without it?

**Comment by noudadrichem** [comment]
We'll take a look at it!

**Comment by electricarts** [comment]
That would be really great if you could hide those weird arrows. There is a setting for icon themes for something like this: 

`"hidesExplorerArrows": true` 

Any chance you'll implement that?

**Comment by coderdiaz** [comment]
@tobiastimm @electricarts  Can you test the implementation?

**Comment by electricarts** [comment]
@coderdiaz Of course, if you tell me what i've to do. Exactly what i've to do.  I'm not that coding hero, just a pixel pusher. ;-)

**Comment by coderdiaz** [comment]
@noudadrichem This issue is outdated. I think this is already solved.

**Comment by noudadrichem** [comment]
True!
