### ISSUE TITLE
[ICON REQUEST] Mint programming language

### ISSUE THREAD

**Issue by s0kil** [Yummygum/city-lights-icons-vsc#7]
### Would be great to support Mint lang.

Repo: https://github.com/mint-lang/mint
Icon: https://github.com/mint-lang/mint-website/blob/master/assets/icon.svg
File_Extension: `.mint`

**Comment by noudadrichem** [comment]
Mint looks nice 😋 I'll add it to the list. You'll hear from us.

**Comment by s0kil** [comment]
Thanks, yes I have been using Mint lately, and it is a great experience.

**Comment by s0kil** [comment]
Seems Project Is Not Maintained.

**Comment by noudadrichem** [comment]
And poof, it is!
