### ISSUE TITLE
What is this icon?

### ISSUE THREAD

**Issue by mittalyashu** [Yummygum/city-lights-icons-vsc#8]
![image](https://user-images.githubusercontent.com/29014463/45968383-6a684300-c04e-11e8-92d7-90030becbccd.png)

This icon doesn't make any sense, try improving it.

**Comment by noudadrichem** [comment]
Dear @mittalyashu,

This is a default icon used as a fallback. Could you be a bit more specific about the things you don't like about this icon?

**Comment by mittalyashu** [comment]
> Could you be a bit more specific about the things you don't like about this icon?

1. This icon is too complicated.
2. The default icon should be much simpler.

_(Something like this)_

![image](https://user-images.githubusercontent.com/29014463/46010640-12c6e780-c0e1-11e8-821c-2e8c63d6cdd6.png)

3. The quality of the icon is poor.

**Comment by noudadrichem** [comment]
I got the feeling you don't like the City Lights suite. 
This is a default icon that fits within the pack and the whole suite. You're not obligated to use the package and you're able to change certain icons within the source code itself to use for yourself.

This is not truly an issue but a design decision you're not agreeing with so i'll close.

**Comment by mittalyashu** [comment]
> I got the feeling you don't like the City Lights suite.

It's not like that, I am using City Lights Theme and I loved it. There are few things in the icon set which I didn't like. That's all.
