### ISSUE TITLE
[Icon update]: Folder

### ISSUE THREAD

**Issue by mittalyashu** [Yummygum/city-lights-icons-vsc#9]
![2018-09-24_23-08-28](https://user-images.githubusercontent.com/29014463/45968554-f24e4d00-c04e-11e8-8158-38c41376086b.gif)

Can you choose any other folder icon, personally I didn't like this folder icon very much.

**Comment by noudadrichem** [comment]
If you don't like the folder icon you're able to change the icon file inside the source files. What the icon should be is up to you. This is a design choice, we're not planning on changing the icon for 8.000 people 😝.

**Comment by mittalyashu** [comment]
> you're able to change the icon file inside the source files.

And where are the source file location?

> This is a design choice, we're not planning on changing the icon for 8.000 people 

Yes, I understand that.

Why don't you try doing some kind of A/B testing _(not sure if it is possible in VS Code extension)_ or ask on twitter about this?

**Comment by noudadrichem** [comment]
Most reactions about the icons are positive, we've added a method to show the colored version of the icons as well. Because of this we decided to keep the folder icon as is. 

Yet again, you can change the icon under `.vscode/extentions/yummygum.city-lights-icon-vsc-[...]/icons/svg/folder-icon.svg`
